### PR TITLE
Fix fetching API endpoints that return array

### PR DESCRIPTION
**Pull request by d4rky-pl**

### CODE REVIEW

**Comment by Enriikke** [comment]
Thanks for taking the time to fix this @d4rky-pl!! Would you mind including some specs to make sure this behaves as expected? Also work through the hound/rubocop violations. :smiley:

**Comment by d4rky-pl** [comment]
I was quick fixing it for a project I was working on but I already tripped on yet another bug. I will look into it and fix this during the weekend :D

**Comment by d4rky-pl** [comment]
How can I check new Hound errors? They don't seem to show up when I amended the previous commit.

**Comment by d4rky-pl** [comment]
Sorry, I see it now. I don't understand the error though, what's inconsistent here as opposed to the rest of the code?

**Comment by splybon** [comment]
So I think that this commit fixes this issue https://github.com/Skookum/bamboozled/commit/2765cc07b409017760c08f65987a15a6dd7af80a

**Comment by d4rky-pl** [comment]
I no longer use this gem anyway, closing the PR

**Pull request closed without merging**
