### PR TITLE
Fix fetching preferredName when getting all fields

### PR DESCRIPTION
**Pull request by artfuldodger**
`nickname` was deprecated and replaced with `preferredName`

https://www.bamboohr.com/api/documentation/employees.php

### CODE REVIEW

**Comment by artfuldodger** [comment]
I rebased this branch off the current master. Here's the relevant bit of the Bamboo docs:

screen shot 2019-02-01 at 2 34 49 pm

**Comment by splybon** [comment]
Hey @artfuldodger thanks for this, looks good!  

Can you rebase off of develop, and point this PR to merge into develop?

**Comment by artfuldodger** [comment]
@splybon You got it! Note that if you want to move forward with #42, this change is included there.

**Comment by splybon** [comment]
Noted. I'll focus more on the other one

**Comment by chrisman** [comment]
Moving forward with #42 👍

Closing this one out

**Pull request closed without merging**
