### PR TITLE
Implement fetching employees via the custom report endpoint

### PR DESCRIPTION
**Pull request by artfuldodger**
Using the custom report endpoint allows us to get a list of the employees with any fields we want in a much more performant manner than iterating through all the employees and getting additional information one-by-one.

### CODE REVIEW

**Comment by splybon** [comment]
hey @artfuldodger saw your comment in the other PR and this is looking good.  Can you fix some of the rubocop errors here?  You can click details in the travis-ci checks, or click the link below

https://travis-ci.org/Skookum/bamboozled/jobs/496020015

**Comment by artfuldodger** [comment]
@splybon I rebased off `develop` and took care of most of the Rubocop issues. For the remaining issue: I find listing one attribute per line in `all_names` preferable to having everything on one line (improves, for example, seeing the diff when something changes), so I'm not sure if anything should actually change there. Happy to tweak to match your preferences though.

**Comment by splybon** [comment]
@artfuldodger I totally agree.

Can you disable that rubocop error then so the linter passes CI?
If you add a comment on or above the method line like below: 
`# rubocop:disable Metrics/MethodLength`

**Comment by artfuldodger** [comment]
@splybon Done! Looks like we're all green now.

**Pull request merged**
